### ISSUE TITLE
[FEAT] Is it possible to display pane with horizontal offset by default

### ISSUE THREAD

**Issue by garj** [tech-systems/panes#230]
I would like to know if there is an option to display the pane horizontally offset-ed at the start instead of in the middle of the screen?

Example:
![Screenshot 2024-01-16 at 10 02 51 PM](https://github.com/tech-systems/panes/assets/7557754/c70ce4e0-9656-43dd-8d0d-f1cb43beb6a7)

**Comment by roman-rr** [comment]
Hi @garj 
Right now you can hardcode with css, like so: 
```css
.pane {
    left: 15px !important;
    margin-left: unset !important;
 }
```

I know this not a best way, but might fill your need as a quick solution.
